config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :kittens
  # Defines the root path route ("/")
  # root "articles#index"
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:notice] = "Successfully created kitten!"
      redirect_to @kitten
    else
      render :new, status: :unprocessable_entity, notice: "You left out something in your form, silly"
    end
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:notice] = "Successfully edited kitten!"
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, status: :see_other, notice: "Successfully deleted kitten!"
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name  %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness %>
    <%= form.number_field :cuteness %>
  </div>

  <div>
    <%= form.label :softness %>
    <%= form.number_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h2>Edit Kitten</h2>

<%= render 'form' %>

<div>
  <%=
    link_to "Delete Kitten", kitten_path(@kitten), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure you want to delete this kitten?"
    }
  %>
</div>

app/views/kittens/index.html.erb
<h2>All Cute Kittens</h2>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to "#{kitten.name}", kitten_path(kitten) %>
      |
      <%=
        link_to "Delete Kitten", kitten_path(kitten), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure you want to delete this kitten?"
        }
      %>
    </li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h2>New Kitten</h2>

<%= render "form" %>

app/views/kittens/show.html.erb
<h2>Kitten</h2>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<div>
  <h5>name: <%= @kitten.name %></h5>
  <p>age: <%= @kitten.age %></p>
  <p>cuteness: <%= @kitten.cuteness %></p>
  <p>softness: <%= @kitten.softness %></p>
</div>

<div>
  <%= link_to "Edit Kitten", edit_kitten_path(@kitten) %>
</div>

<div>
  <%=
    link_to "Delete Kitten", kitten_path(@kitten), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure you want to delete this kitten?"
    }
  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>